// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdrihatnrdsdmaonzheh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkcmloYXRucmRzZG1hb256aGVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDIyNzgsImV4cCI6MjA2MTQxODI3OH0.LeT-6IPFo4iO3QB9d98HltY4atlLPP9F0PM6Ma2uKBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);